name: Publish Patch to Docker
on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write
  security-events: write
  pull-requests: write
jobs:
  build-publish-docker:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-docker-versioned.yaml@v2.5
    with: 
      cloud_provider: 'default'
      release_type: 'Patch'
    secrets: inherit
