name: Release UID2 Optout Image
run-name: ${{ inputs.release_type == 'Snapshot' && 'Publish Pre-release' || format('Release {0}', inputs.release_type)}} Docker Image by @${{ github.actor }}  
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: The type of release
        options:
        - Major
        - Minor
        - Patch
        - Snapshot
      operator_image_version:
        description: 'Image: Operator image version'
        type: string
        default: latest
      core_image_version:
        description: 'Image: Core image version'
        type: string
        default: latest
      e2e_image_version:
        description: 'Image: E2E image version'
        type: string
        default: latest
      operator_branch:
        description: 'Config: Operator branch for config'
        type: string
        default: main
      core_branch:
        description: 'Config: Core branch for config'
        type: string
        default: main
      admin_branch:
        description: 'Config: Admin branch for config'
        type: string
        default: main
      vulnerability_severity:
        description: The severity to fail the workflow if such vulnerability is detected. DO NOT override it unless a Jira ticket is raised.
        type: choice
        options:
        - CRITICAL,HIGH
        - CRITICAL,HIGH,MEDIUM
        - CRITICAL (DO NOT use if JIRA ticket not raised)

jobs:
  Image:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-java-to-docker-versioned.yaml@v3
    with: 
      release_type: ${{ inputs.release_type }}
      vulnerability_severity: ${{ inputs.vulnerability_severity }}
      java_version: 21
    secrets: inherit

  e2e-test:
    name: E2E Test
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-run-e2e-tests.yaml@v3
    needs: Image
    with:
      operator_type: public
      operator_image_version: ${{ inputs.operator_image_version }}
      core_image_version: ${{ inputs.core_image_version }}
      optout_image_version: ${{ needs.image.outputs.image_tag }}
      e2e_image_version: ${{ inputs.e2e_image_version }}
      branch_core: ${{ inputs.core_branch }}
      branch_optout: ${{ github.ref }}
      branch_admin: ${{ inputs.admin_branch }}
      operator_branch: ${{ inputs.operator_branch }}
    secrets: inherit
  